name: ${NAME:?error}

services:

 nginx:
  container_name: nginx
  env_file: .env
  build: requirements/nginx
  ports: 
   - "4443:443"
  networks:
   - inception
  volumes:
   - wordpress_files:/var/www/html
  depends_on:
   - wordpress
  restart: on-failure

 wordpress:
  container_name: wordpress
  env_file: .env
  build: requirements/wordpress
  networks:
   - inception
   - backend
  volumes:
   - wordpress_files:/var/www/html
  depends_on:
   - mariadb
  secrets:
   - db_credentials
   - wp_credentials
  restart: on-failure

 mariadb:
  container_name: mariadb
  env_file: .env
  build: requirements/mariadb
  networks:
   - backend
  volumes:
   - database:/var/lib/mysql
  secrets:
   - db_credentials
  restart: on-failure


networks:
 inception:
  driver: bridge
 backend:
  driver: bridge


volumes:
 wordpress_files:
  driver: local
  driver_opts:
    type: none
    device: /home/cluby/data/wordpress
    o: bind
 database:
  driver: local
  driver_opts:
    type: none
    device: /home/cluby/data/mariadb
    o: bind


secrets:
 db_credentials:
  file: ../secrets/db_credentials
 wp_credentials:
  file: ../secrets/wp_credentials
