name: ${NAME:?error}

services:

 nginx:
  container_name: nginx
  env_file: .env
  build: requirements/nginx
  ports: 
   - "4443:443"
  networks:
   - inception
  volumes:
   - wordpress_files:/var/www/html
  depends_on:
   - wordpress
  

 wordpress:
  container_name: wordpress
  env_file: .env
  build: requirements/wordpress
  networks:
   - inception
   - backend
  volumes:
   - wordpress_files:/var/www/html
  expose:
   - 9000  
   - 3306
  depends_on:
   - mariadb

 mariadb:
  container_name: mariadb
  env_file: .env
  build: requirements/mariadb
  networks:
   - backend
  volumes:
   - database:/var/lib/mysql
  expose:
   - 3306


networks:
 inception:
  driver: bridge
 backend:
  driver: bridge

volumes:
 wordpress_files:
  driver: local
  driver_opts:
    type: none
    device: ./test/wordpress
    o: bind
 database:
  driver: local
  driver_opts:
    type: none
    device: ./database
    o: bind
